#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
  systemctl try-restart pve-cluster.service || true
  systemctl try-restart pvedaemon.service || true
  systemctl try-restart pvestatd.service || true
  systemctl try-restart pveproxy.service || true
  systemctl try-restart pvescheduler.service || true
fi
